include "/etc/bind/named.conf.options";
include "/etc/bind/rndc.key";

controls {
    inet 127.0.0.1 port 953
        allow { 127.0.0.1; 10.10.0.0/24; }
        keys { "rndc-key"; };
};

logging {
    channel bind_default {
        stderr;
        severity info;
        print-time yes;
        print-category yes;
        print-severity yes;
    };

    channel bind_queries {
        stderr;
        severity info;
        print-time yes;
        print-category yes;
        print-severity yes;
    };

    channel bind_security {
        stderr;
        severity info;
        print-time yes;
        print-category yes;
        print-severity yes;
    };

    category default { bind_default; };
    category queries { bind_queries; };
    category security { bind_security; };
};

include "/etc/bind/named.conf.views";
