include "/etc/bind/named.conf.options";

logging {
    channel bind_default {
        stderr;
        severity info;
        print-time yes;
        print-category yes;
        print-severity yes;
    };

    channel bind_security {
        stderr;
        severity info;
        print-time yes;
        print-category yes;
        print-severity yes;
    };

    category default { bind_default; };
    category security { bind_security; };
};

include "/etc/bind/named.conf.local";
